# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f69f25562a8dec22983f4fb755e06e090513f52a78962f805d6f1e9dcc2ceb4886f4c5822221ce6c4beb583daa5a8336c923c4a85b05287ed0ae22bd6dd9a293

test:
  secret_key_base: d1f982e18fbc7ddc9ec2278c216d72090bd6a3dfa21ecd26827ff53c1e71ecf5427877ae79e967989149e2d3b54800cdcb389d957d8cbae40b42689ffd88f090

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
